import type { AIModel } from '../types';

export const MODEL_ICON = 'https://img.icons8.com/?size=100&id=77iHQnb2ZTjZ&format=png&color=1A1A1A';

export const AI_MODELS: AIModel[] = [
  {
    id: 'mistralai/mistral-nemo',
    name: 'MoSeek Nemo',
    description: 'Mistral Nemo 12B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-rose-400 to-pink-500',
  },
  {
    id: 'openai/gpt-oss-120b:free',
    name: 'MoSeek GPT 120B',
    description: 'GPT OSS 120B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-green-400 to-emerald-500',
  },
  {
    id: 'z-ai/glm-4.5-air:free',
    name: 'MoSeek GLM 4.5',
    description: 'GLM 4.5 Air',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-400 to-indigo-500',
  },
  {
    id: 'stepfun/step-3.5-flash:free',
    name: 'MoSeek Step 3.5',
    description: 'Step 3.5 Flash',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-cyan-400 to-blue-500',
  },
  {
    id: 'arcee-ai/trinity-large-preview:free',
    name: 'MoSeek Trinity Large',
    description: 'Trinity Large Preview',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-purple-400 to-violet-500',
  },
  {
    id: 'arcee-ai/trinity-mini:free',
    name: 'MoSeek Trinity Mini',
    description: 'Trinity Mini',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-fuchsia-400 to-purple-500',
  },
  {
    id: 'upstage/solar-pro-3:free',
    name: 'MoSeek Solar Pro 3',
    description: 'Solar Pro 3',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-orange-400 to-red-500',
  },
  {
    id: 'nvidia/nemotron-3-nano-30b-a3b:free',
    name: 'MoSeek Nemotron 30B',
    description: 'Nemotron 3 Nano 30B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-lime-400 to-green-500',
  },
  {
    id: 'nvidia/nemotron-nano-12b-v2-vl:free',
    name: 'MoSeek Nemotron 12B',
    description: 'Nemotron Nano 12B Vision',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-emerald-400 to-teal-500',
  },
  {
    id: 'liquid/lfm-2.5-1.2b-thinking:free',
    name: 'MoSeek Liquid Think',
    description: 'LFM 2.5 Thinking',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-sky-400 to-cyan-500',
  },
  {
    id: 'liquid/lfm-2.5-1.2b-instruct:free',
    name: 'MoSeek Liquid',
    description: 'LFM 2.5 Instruct',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-teal-400 to-sky-500',
  },
  {
    id: 'google/gemma-3n-e2b-it:free',
    name: 'MoSeek Gemma 3N',
    description: 'Gemma 3N E2B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-red-400 to-orange-500',
  },
  {
    id: 'tngtech/tng-r1t-chimera:free',
    name: 'MoSeek Chimera R1T',
    description: 'TNG R1T Chimera',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-indigo-400 to-blue-500',
  },
  {
    id: 'tngtech/deepseek-r1t-chimera:free',
    name: 'MoSeek DS Chimera',
    description: 'DeepSeek R1T Chimera',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-violet-400 to-indigo-500',
  },
  {
    id: 'tngtech/deepseek-r1t2-chimera:free',
    name: 'MoSeek DS Chimera V2',
    description: 'DeepSeek R1T2 Chimera',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-pink-400 to-rose-500',
  },
];

export const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
